import {
	ApartmentOutlined,
	BellOutlined,
	BookOutlined,
	CalendarOutlined,
	CheckCircleOutlined,
	CiOutlined,
	ClockCircleOutlined,
	CloseCircleOutlined,
	CloudOutlined,
	CodepenOutlined,
	ContainerOutlined,
	DeleteOutlined,
	DownloadOutlined,
	DragOutlined,
	EditOutlined,
	EnvironmentOutlined,
	EyeInvisibleOutlined,
	EyeOutlined,
	FileTextOutlined,
	FlagOutlined,
	FormOutlined,
	GiftOutlined,
	GlobalOutlined,
	HeartOutlined,
	HomeFilled,
	InfoCircleOutlined,
	LockOutlined,
	MailOutlined,
	MenuOutlined,
	MinusCircleOutlined,
	MoneyCollectOutlined,
	NumberOutlined,
	PhoneOutlined,
	PictureOutlined,
	PlusCircleOutlined,
	ProfileOutlined,
	RocketOutlined,
	SafetyCertificateOutlined,
	SearchOutlined,
	SettingOutlined,
	ShoppingCartOutlined,
	StarOutlined,
	TagOutlined,
	TeamOutlined,
	TrophyOutlined,
	UnlockOutlined,
	UploadOutlined,
	UserOutlined,
	VideoCameraOutlined,
	WarningOutlined,
	WechatOutlined,
	WindowsOutlined,
	DatabaseFilled,
} from "@ant-design/icons";
import {
	IconAlarm,
	IconAlertCircle,
	IconAlertTriangle,
	IconBell,
	IconBellRinging,
	IconBluetooth,
	IconCalendar,
	IconCalendarEvent,
	IconCamera,
	IconChartBar,
	IconChartDots,
	IconChartLine,
	IconChartPie,
	IconCheck,
	IconCircleCheck,
	IconCircleX,
	IconClock,
	IconCloud,
	IconCloudDownload,
	IconCloudUpload,
	IconDatabase,
	IconDownload,
	IconEdit,
	IconEye,
	IconEyeOff,
	IconFile,
	IconFolder,
	IconHeart,
	IconHome,
	IconInfoCircle,
	IconKey,
	IconLayoutDashboard,
	IconLock,
	IconLockOpen,
	IconMail,
	IconMailOpened,
	IconMapPin,
	IconMenu2,
	IconMinus,
	IconMusic,
	IconPencil,
	IconPhone,
	IconPhoneCall,
	IconPhoto,
	IconPlus,
	IconSearch,
	IconSettings,
	IconShield,
	IconShieldCheck,
	IconStar,
	IconStarFilled,
	IconTrash,
	IconUpload,
	IconUser,
	IconUserCheck,
	IconUserPlus,
	IconUsers,
	IconVideo,
	IconWifi,
	IconX,
} from "@tabler/icons-react";

// antd 图标映射表
export const IconMap: Record<string, React.ReactNode> = {
	ApartmentOutlined: <ApartmentOutlined />,
	BellOutlined: <BellOutlined />,
	BookOutlined: <BookOutlined />,
	CalendarOutlined: <CalendarOutlined />,
	CheckCircleOutlined: <CheckCircleOutlined />,
	CiOutlined: <CiOutlined />,
	ClockCircleOutlined: <ClockCircleOutlined />,
	CloseCircleOutlined: <CloseCircleOutlined />,
	CloudOutlined: <CloudOutlined />,
	CodepenOutlined: <CodepenOutlined />,
	ContainerOutlined: <ContainerOutlined />,
	DeleteOutlined: <DeleteOutlined />,
	DownloadOutlined: <DownloadOutlined />,
	DragOutlined: <DragOutlined />,
	EditOutlined: <EditOutlined />,
	EnvironmentOutlined: <EnvironmentOutlined />,
	EyeInvisibleOutlined: <EyeInvisibleOutlined />,
	EyeOutlined: <EyeOutlined />,
	FileTextOutlined: <FileTextOutlined />,
	FlagOutlined: <FlagOutlined />,
	FormOutlined: <FormOutlined />,
	GiftOutlined: <GiftOutlined />,
	GlobalOutlined: <GlobalOutlined />,
	HeartOutlined: <HeartOutlined />,
	HomeFilled: <HomeFilled />,
	InfoCircleOutlined: <InfoCircleOutlined />,
	LockOutlined: <LockOutlined />,
	MailOutlined: <MailOutlined />,
	MenuOutlined: <MenuOutlined />,
	MinusCircleOutlined: <MinusCircleOutlined />,
	MoneyCollectOutlined: <MoneyCollectOutlined />,
	NumberOutlined: <NumberOutlined />,
	PhoneOutlined: <PhoneOutlined />,
	PictureOutlined: <PictureOutlined />,
	PlusCircleOutlined: <PlusCircleOutlined />,
	ProfileOutlined: <ProfileOutlined />,
	RocketOutlined: <RocketOutlined />,
	SafetyCertificateOutlined: <SafetyCertificateOutlined />,
	SearchOutlined: <SearchOutlined />,
	SettingOutlined: <SettingOutlined />,
	ShoppingCartOutlined: <ShoppingCartOutlined />,
	StarOutlined: <StarOutlined />,
	TagOutlined: <TagOutlined />,
	TeamOutlined: <TeamOutlined />,
	TrophyOutlined: <TrophyOutlined />,
	UnlockOutlined: <UnlockOutlined />,
	UploadOutlined: <UploadOutlined />,
	UserOutlined: <UserOutlined />,
	VideoCameraOutlined: <VideoCameraOutlined />,
	WarningOutlined: <WarningOutlined />,
	WechatOutlined: <WechatOutlined />,
	WindowsOutlined: <WindowsOutlined />,
	DatabaseFilled: <DatabaseFilled />,
};

// @tabler/icons-react 图标映射表
export const TablerIconMap: Record<string, React.ReactNode> = {
	IconAlarm: <IconAlarm stroke={2} />,
	IconAlertCircle: <IconAlertCircle stroke={2} />,
	IconAlertTriangle: <IconAlertTriangle stroke={2} />,
	IconBell: <IconBell stroke={2} />,
	IconBellRinging: <IconBellRinging stroke={2} />,
	IconBluetooth: <IconBluetooth stroke={2} />,
	IconCalendar: <IconCalendar stroke={2} />,
	IconCalendarEvent: <IconCalendarEvent stroke={2} />,
	IconCamera: <IconCamera stroke={2} />,
	IconChartBar: <IconChartBar stroke={2} />,
	IconChartDots: <IconChartDots stroke={2} />,
	IconChartLine: <IconChartLine stroke={2} />,
	IconChartPie: <IconChartPie stroke={2} />,
	IconCheck: <IconCheck stroke={2} />,
	IconCircleCheck: <IconCircleCheck stroke={2} />,
	IconCircleX: <IconCircleX stroke={2} />,
	IconClock: <IconClock stroke={2} />,
	IconCloud: <IconCloud stroke={2} />,
	IconCloudDownload: <IconCloudDownload stroke={2} />,
	IconCloudUpload: <IconCloudUpload stroke={2} />,
	IconDownload: <IconDownload stroke={2} />,
	IconEdit: <IconEdit stroke={2} />,
	IconEye: <IconEye stroke={2} />,
	IconEyeOff: <IconEyeOff stroke={2} />,
	IconFile: <IconFile stroke={2} />,
	IconFolder: <IconFolder stroke={2} />,
	IconHeart: <IconHeart stroke={2} />,
	IconHome: <IconHome stroke={2} />,
	IconInfoCircle: <IconInfoCircle stroke={2} />,
	IconKey: <IconKey stroke={2} />,
	IconLayoutDashboard: <IconLayoutDashboard stroke={2} />,
	IconLock: <IconLock stroke={2} />,
	IconLockOpen: <IconLockOpen stroke={2} />,
	IconMail: <IconMail stroke={2} />,
	IconMailOpened: <IconMailOpened stroke={2} />,
	IconMapPin: <IconMapPin stroke={2} />,
	IconMenu2: <IconMenu2 stroke={2} />,
	IconMinus: <IconMinus stroke={2} />,
	IconMusic: <IconMusic stroke={2} />,
	IconPencil: <IconPencil stroke={2} />,
	IconPhone: <IconPhone stroke={2} />,
	IconPhoneCall: <IconPhoneCall stroke={2} />,
	IconPhoto: <IconPhoto stroke={2} />,
	IconPlus: <IconPlus stroke={2} />,
	IconSearch: <IconSearch stroke={2} />,
	IconSettings: <IconSettings stroke={2} />,
	IconShield: <IconShield stroke={2} />,
	IconShieldCheck: <IconShieldCheck stroke={2} />,
	IconStar: <IconStar stroke={2} />,
	IconStarFilled: <IconStarFilled stroke={2} />,
	IconTrash: <IconTrash stroke={2} />,
	IconUpload: <IconUpload stroke={2} />,
	IconUser: <IconUser stroke={2} />,
	IconUserCheck: <IconUserCheck stroke={2} />,
	IconUserPlus: <IconUserPlus stroke={2} />,
	IconUsers: <IconUsers stroke={2} />,
	IconVideo: <IconVideo stroke={2} />,
	IconWifi: <IconWifi stroke={2} />,
	IconX: <IconX stroke={2} />,
	IconDatabase: <IconDatabase stroke={2} />,
};
